src/muipicky/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView. as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

src/muipicky/muipicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name = 'home'),
    url(r'^register/$', RegisterView.as_view(), name = 'register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name = 'activate'),
    url(r'^login/$', LoginView.as_view(), name = 'login'),
    url(r'^logout/$', LogoutView.as_view(), name = 'logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name = 'follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html'), name = 'about'),
    url(r'^contact/$', TemplateView.as_view(template_name = 'contact.html'), name = 'contact'),
]

src/muipicky/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/muipicky/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}

<form method='POST'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>


{% if form.instance %}
<h1>{{ form.instance.restaurant }}</h1>
{% endif %}

src/muipicky/templates/snippets/js.html
<!-- Latest compiled and minified JavaScript -->
<script src='https://code.jquery.com/jquery-3.2.1.min.js'</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/muipicky/templates/snippets/nav.html
<div class='container'>
    
<h1>MUY PICKY</h1>

<!--<a href="/"> Home </a><br>
<a href="/restaurants"> Restaurants </a><br>
<a href="/about"> About </a><br>
<a href="/contact"> Contact </a>-->

<a href='{% url "home" %}'> Home </a>
<!--using this is better than above because it matches the path (from url.py) with the url name 
from here and there. This is handy because you don't need to remember any complicated url paths, just 
need to know the url name-->
<a href='{% url "about" %}'> About </a>
<a href='{% url "contact" %}'> Contact </a>
{% if  request.user.is_authenticated %}
<a href='{% url "restaurants:list" %}'> Restaurants </a>
<a href='{% url "menus:list" %}'> Menu Items </a>
{% endif %}
</div>

src/muipicky/templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>